In [2]:
import pandas as pd
import torch
from sklearn.metrics import log_loss, roc_auc_score  
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

# from deepctr_torch.inputs import SparseFeat, DenseFeat, get_feature_names

In [5]:
train_data = pd.read_table("/Users/Edward/data-competitions/CTR/dac/train.txt")
test_data = pd.read_table("/Users/Edward/data-competitions/CTR/dac/test.txt")

In [6]:
train_data.head()

,0,1,1.1,5,0.1,1382,4,15,2,181,...,e5ba7672,f54016b9,21ddcdc9,b1252a9d,07b5194c,Unnamed: 35,3a171ecb,c5c50484,e8b83407,9727dd16
0,0,2.0,0,44.0,1.0,102.0,8.0,2.0,2.0,4.0,...,07c540c4,b04e4670,21ddcdc9,5840adea,60f6221e,NaN,3a171ecb,43f13e8b,e8b83407,731c3655
1,0,2.0,0,1.0,14.0,767.0,89.0,4.0,2.0,245.0,...,8efede7f,3412118d,NaN,NaN,e587c466,ad3062eb,3a171ecb,3b183c5c,NaN,NaN
2,0,NaN,893,NaN,NaN,4392.0,NaN,0.0,0.0,0.0,...,1e88c74f,74ef3502,NaN,NaN,6b3a5ca6,NaN,3a171ecb,9117a34a,NaN,NaN
3,0,3.0,-1,NaN,0.0,2.0,0.0,3.0,0.0,0.0,...,1e88c74f,26b3c7a7,NaN,NaN,21c9516a,NaN,32c7478e,b34f3128,NaN,NaN
4,0,NaN,-1,NaN,NaN,12824.0,NaN,0.0,0.0,6.0,...,776ce399,92555263,NaN,NaN,242bb710,8ec974f4,be7c41b4,72c78f11,NaN,NaN